export const types = {
  INSERT_USER: 'INSERT_USER',
  GET_LOGIN: 'GET_LOGIN',

  USER_SUCCESS: 'USER_SUCCESS',
  USER_FAILURE: 'USER_FAILURE',
  USER_RESET: 'USER_RESET',

  INSERT_EMPLOYEE: 'INSERT_EMPLOYEE',
  // INSERT_EMPLOYEE_SUCCESS: 'INSERT_EMPLOYEE_SUCCESS',
  // INSERT_EMPLOYEE_FAILURE: 'INSERT_EMPLOYEE_FAILURE',
  // INSERT_EMPLOYEE_RESET: 'INSERT_EMPLOYEE_RESET',

  GET_EMPLOYEE: 'GET_EMPLOYEE',
  GET_EMPLOYEE_SUCCESS: 'GET_EMPLOYEE_SUCCESS',
  GET_EMPLOYEE_FAILURE: 'GET_EMPLOYEE_FAILURE',
  GET_EMPLOYEE_RESET: 'GET_EMPLOYEE_RESET',

  GET_EMPLOYEE_DETAIL: 'GET_EMPLOYEE_DETAIL',
  GET_EMPLOYEE_DETAIL_SUCCESS: 'GET_EMPLOYEE_DETAIL_SUCCESS',
  GET_EMPLOYEE_DETAIL_FAILURE: 'GET_EMPLOYEE_DETAIL_FAILURE',
  GET_EMPLOYEE_DETAIL_RESET: 'GET_EMPLOYEE_DETAIL_RESET',

  GET_PRODUCT: 'GET_PRODUCT',
  GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
  GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',
  GET_PRODUCT_RESET: 'GET_PRODUCT_RESET',

  GET_PRODUCT_DETAIL: 'GET_PRODUCT_DETAIL',
  GET_PRODUCT_DETAIL_SUCCESS: 'GET_PRODUCT_DETAIL_SUCCESS',
  GET_PRODUCT_DETAIL_FAILURE: 'GET_PRODUCT_DETAIL_FAILURE',
  GET_PRODUCT_DETAIL_RESET: 'GET_PRODUCT_DETAIL_RESET',

  CHARGE_PAYMENT: 'CHARGE_PAYMENT',
  STATUS_PAYMENT: 'STATUS_PAYMENT',

  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILURE: 'PAYMENT_FAILURE',
  PAYMENT_RESET: 'PAYMENT_RESET',

  GET_PAYMENT: 'GET_PAYMENT',
  GET_PAYMENT_SUCCESS: 'GET_PAYMENT_SUCCESS',
  GET_PAYMENT_FAILURE: 'GET_PAYMENT_FAILURE',
  GET_PAYMENT_RESET: 'GET_PAYMENT_RESET',
};
